<a href="https://colab.research.google.com/github/Bryantoropn/Datmin-Manipulasi-array-menggunakan-numpy/blob/main/Manipulasi_array_menggunakan_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*italicised text*

In [ ]:
import numpy as np


In [ ]:
import numpy as np
arr = np.array([[4,4,5],[7,6,4],[9,7,4],[6,3,7]])  
print(arr) 


[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


In [ ]:
import numpy 
arr = numpy.array([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],[[2,1,2],[9,8,5],[3,7,3],[4,9,9]],[[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])  
print(arr) 

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0:2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np
arr = np.array([[1,8,8,2], [8,2,1,2],[10,1,4,7],[1,4,7,8],[8,2,3,4]])
arr[1::2] += 1
print(arr)
arr[:,0::2] += 2
print(arr)

In [ ]:
import numpy as np
arr = np.array(
    [
     [
      [7,8,5],
      [4,7,7],
      [7,1,9],
      [5,4,10],
     ],
     [
      [2,1,2],
      [9,8,5],
      [3,7,3],
      [4,9,9],
     ],
     [
      [2,9,3],
      [2,4,8],
      [1,6,6],
      [8,1,3]
     ]
    ]
)

print(arr[::-1])

In [ ]:
import numpy as np
arr = np.array(
    [
     [
      [7,8,5],
      [4,7,7],
      [7,1,9],
      [5,4,10],
     ],
     [
      [2,1,2],
      [9,8,5],
      [3,7,3],
      [4,9,9],
     ],
     [
      [2,9,3],
      [2,4,8],
      [1,6,6],
      [8,1,3]
     ]
    ]
).reshape(6,6)

print(arr)

In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2),axis=1)  
print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr = np.array([
      [5,10,10,7],          
      [7,8,4,10],
      [9,10,2,5],
      [1,8,9,3],
      [6,10,5,2],
      [4,6,9,4]
])

kiri_atas = arr[:3,:2] #5,10,7,8,9,10
kiri_bawah = arr[3:,:2] #1,8,6,10,4,6
kanan_atas = arr[:3,2:] #10,7,4,10,2,5
kanan_bawah = arr[3:,2:] #9,3,5,2,9,4
atas = np.concatenate((kanan_bawah,kiri_bawah),axis=1)
bawah = np.concatenate((kanan_atas,kiri_atas),axis=1)
arr_baru = np.concatenate((atas,bawah),axis=0)
print(arr_baru)

[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
